# generated by datamodel-codegen:
#   filename:  421.json
#   timestamp: 2026-01-26T14:54:16+00:00

from __future__ import annotations

from pydantic import BaseModel, RootModel


class DateTimePlacePersonText(BaseModel):
    cn: str | None


class Course(BaseModel):
    id: int | None
    code: str | None
    cn: str | None
    en: str | None


class CourseType(BaseModel):
    cn: str | None
    en: str | None


class CourseGradation(BaseModel):
    cn: str | None
    en: str | None


class CourseCategory(BaseModel):
    cn: str | None
    en: str | None


class CourseClassify(BaseModel):
    cn: str | None
    en: str | None


class OpenDepartment(BaseModel):
    college: bool | None
    code: str | None
    cn: str | None
    en: str | None


class Campus(BaseModel):
    cn: str | None
    en: str | None


class ExamMode(BaseModel):
    cn: str | None
    en: str | None


class TeachLang(BaseModel):
    cn: str | None
    en: str | None


class Education(BaseModel):
    cn: str | None
    en: str | None


class ClassType(BaseModel):
    cn: str | None
    en: str | None


class TeacherAssignmentListItem(BaseModel):
    cn: str | None
    en: str | None
    departmentCode: str | None


class AdminClass(BaseModel):
    cn: str | None
    en: str | None


class TeachLessonListItem(BaseModel):
    id: int | None
    code: str | None
    period: int | None
    periodsPerWeek: float | None
    credits: float | None
    dateTimePlaceText: str | None
    dateTimePlacePersonText: DateTimePlacePersonText | None
    stdCount: int | None
    limitCount: int | None
    graduateAndPostgraduate: bool | None
    course: Course | None
    courseType: CourseType | None
    courseGradation: CourseGradation | None
    courseCategory: CourseCategory | None
    courseClassify: CourseClassify | None
    openDepartment: OpenDepartment | None
    campus: Campus | None
    examMode: ExamMode | None
    teachLang: TeachLang | None
    education: Education | None
    classType: ClassType | None
    teacherAssignmentList: list[TeacherAssignmentListItem] | None
    adminClasses: list[AdminClass] | None


class TeachLessonListResponse(RootModel[list[TeachLessonListItem] | None]):
    root: list[TeachLessonListItem] | None
