# generated by datamodel-codegen:
#   filename:  401.json
#   timestamp: 2026-01-26T15:24:44+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, RootModel


class ExamBatch(BaseModel):
    id: int
    name: str


class ExamRoom(BaseModel):
    room: str
    count: int


class ClassType(BaseModel):
    en: str
    cn: str


class Course(BaseModel):
    id: int
    code: str
    credits: float
    en: str
    cn: str


class CourseCategory(BaseModel):
    en: str | None
    cn: str


class CourseGradation(BaseModel):
    en: str
    cn: str


class CourseType(BaseModel):
    en: str
    cn: str


class Education(BaseModel):
    en: str
    cn: str


class OpenDepartment(BaseModel):
    code: str
    en: str
    cn: str


class TeacherAssignmentListItem(BaseModel):
    id: int
    en: str | None
    cn: str


class Lesson(BaseModel):
    actualPeriods: int
    classType: ClassType
    code: str
    compulsory: bool | None
    course: Course
    courseCategory: CourseCategory
    courseGradation: CourseGradation
    courseType: CourseType
    education: Education
    graduateAndPostgraduate: bool
    id: int
    openDepartment: OpenDepartment
    teacherAssignmentList: list[TeacherAssignmentListItem]


class Monitor(BaseModel):
    id: int
    en: str | None
    cn: str


class ModelItem(BaseModel):
    id: int
    examType: int
    startTime: int
    endTime: int
    examBatch: ExamBatch
    examDate: str
    examRooms: list[ExamRoom]
    examTakeCount: int
    examMode: str
    lesson: Lesson
    monitors: list[Monitor]
    spvisors: list[Any]
    grades: str | None
    adminclasseNames: str | None


class Model(RootModel[list[ModelItem]]):
    root: list[ModelItem]
