# generated by datamodel-codegen:
#   filename:  list.json
#   timestamp: 2026-01-26T14:53:33+00:00

from __future__ import annotations

from pydantic import BaseModel, RootModel


class ModelItem(BaseModel):
    id: int
    nameZh: str
    code: str
    start: str
    end: str
    isLast: bool


class Model(RootModel[list[ModelItem]]):
    root: list[ModelItem]
