# generated by datamodel-codegen:
#   filename:  401.json
#   timestamp: 2026-01-26T15:24:44+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, RootModel


class ExamBatch(BaseModel):
    id: int | None
    name: str | None


class ExamRoom(BaseModel):
    room: str | None
    count: int | None


class ClassType(BaseModel):
    en: str | None
    cn: str | None


class Course(BaseModel):
    id: int | None
    code: str | None
    credits: float | None
    en: str | None
    cn: str | None


class CourseCategory(BaseModel):
    en: str | None
    cn: str | None


class CourseGradation(BaseModel):
    en: str | None
    cn: str | None


class CourseType(BaseModel):
    en: str | None
    cn: str | None


class Education(BaseModel):
    en: str | None
    cn: str | None


class OpenDepartment(BaseModel):
    code: str | None
    en: str | None
    cn: str | None


class TeacherAssignmentListItem(BaseModel):
    id: int | None
    en: str | None
    cn: str | None


class Lesson(BaseModel):
    actualPeriods: int | None
    classType: ClassType | None
    code: str | None
    compulsory: bool | None
    course: Course | None
    courseCategory: CourseCategory | None
    courseGradation: CourseGradation | None
    courseType: CourseType | None
    education: Education | None
    graduateAndPostgraduate: bool | None
    id: int | None
    openDepartment: OpenDepartment | None
    teacherAssignmentList: list[TeacherAssignmentListItem] | None


class Monitor(BaseModel):
    id: int | None
    en: str | None
    cn: str | None


class TeachExamListItem(BaseModel):
    id: int | None
    examType: int | None
    startTime: int | None
    endTime: int | None
    examBatch: ExamBatch | None
    examDate: str | None
    examRooms: list[ExamRoom] | None
    examTakeCount: int | None
    examMode: str | None
    lesson: Lesson | None
    monitors: list[Monitor] | None
    spvisors: list[Any] | None
    grades: str | None
    adminclasseNames: str | None


class TeachExamListResponse(RootModel[list[TeachExamListItem] | None]):
    root: list[TeachExamListItem] | None
