# generated by datamodel-codegen:
#   filename:  421.json
#   timestamp: 2026-01-26T14:54:16+00:00

from __future__ import annotations

from pydantic import BaseModel, RootModel


class DateTimePlacePersonText(BaseModel):
    cn: str | None


class Course(BaseModel):
    id: int
    code: str
    cn: str
    en: str


class CourseType(BaseModel):
    cn: str | None
    en: str | None


class CourseGradation(BaseModel):
    cn: str
    en: str


class CourseCategory(BaseModel):
    cn: str
    en: str | None


class CourseClassify(BaseModel):
    cn: str | None
    en: str | None


class OpenDepartment(BaseModel):
    college: bool
    code: str
    cn: str
    en: str


class Campus(BaseModel):
    cn: str
    en: str


class ExamMode(BaseModel):
    cn: str
    en: str


class TeachLang(BaseModel):
    cn: str | None
    en: str | None


class Education(BaseModel):
    cn: str
    en: str


class ClassType(BaseModel):
    cn: str
    en: str


class TeacherAssignmentListItem(BaseModel):
    cn: str
    en: str | None
    departmentCode: str


class AdminClass(BaseModel):
    cn: str
    en: str | None


class ModelItem(BaseModel):
    id: int
    code: str
    period: int
    periodsPerWeek: float | None
    credits: float
    dateTimePlaceText: str | None
    dateTimePlacePersonText: DateTimePlacePersonText
    stdCount: int
    limitCount: int
    graduateAndPostgraduate: bool
    course: Course
    courseType: CourseType
    courseGradation: CourseGradation
    courseCategory: CourseCategory
    courseClassify: CourseClassify
    openDepartment: OpenDepartment
    campus: Campus
    examMode: ExamMode
    teachLang: TeachLang
    education: Education
    classType: ClassType
    teacherAssignmentList: list[TeacherAssignmentListItem]
    adminClasses: list[AdminClass]


class Model(RootModel[list[ModelItem]]):
    root: list[ModelItem]
