# generated by datamodel-codegen:
#   filename:  list.json
#   timestamp: 2026-01-26T14:53:33+00:00

from __future__ import annotations

from pydantic import BaseModel, RootModel


class TeachSemesterListItem(BaseModel):
    id: int | None
    nameZh: str | None
    code: str | None
    start: str | None
    end: str | None
    isLast: bool | None


class TeachSemesterListResponse(RootModel[list[TeachSemesterListItem] | None]):
    root: list[TeachSemesterListItem] | None
