# generated by datamodel-codegen:
#   filename:  497890.json
#   timestamp: 2026-01-26T14:47:58+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class RequiredPeriodInfo(BaseModel):
    total: float | None
    weeks: int | None
    theory: float | None
    theoryUnit: float | None
    requireTheory: float | None
    practice: float | None
    practiceUnit: float | None
    requirePractice: float | None
    test: float | None
    testUnit: float | None
    requireTest: float | None
    experiment: float | None
    experimentUnit: float | None
    requireExperiment: float | None
    machine: float | None
    machineUnit: float | None
    requireMachine: float | None
    design: float | None
    designUnit: float | None
    requireDesign: float | None
    periodsPerWeek: float | None
    timesPerWeek: int | None


class DateTimeText(BaseModel):
    textZh: str | None
    textEn: str | None
    text: str | None


class DateTimePlaceText(BaseModel):
    textZh: str | None
    textEn: str | None
    text: str | None


class DateTimePlacePersonText(BaseModel):
    textZh: str | None
    textEn: str | None
    text: str | None


class RoomSeatText(BaseModel):
    textZh: str | None
    textEn: str | None
    text: str | None


class ScheduleText(BaseModel):
    dateTimeText: DateTimeText | None
    dateTimePlaceText: DateTimePlaceText | None
    dateTimePlacePersonText: DateTimePlacePersonText | None
    roomSeatText: RoomSeatText | None


class TimeTableLayout(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    enabled: bool | None


class BizType(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None


class Calendar(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None


class Semester(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    code: str | None
    calendar: Calendar | None
    schoolYear: str | None
    startDate: str | None
    endDate: str | None
    weekStartOnSunday: bool | None
    countInTerm: bool | None
    season: str | None
    enabled: bool | None
    fileInfo: int | None


class PeriodInfo(BaseModel):
    total: float | None
    weeks: int | None
    theory: float | None
    theoryUnit: float | None
    requireTheory: float | None
    practice: float | None
    practiceUnit: float | None
    requirePractice: float | None
    test: float | None
    testUnit: float | None
    requireTest: float | None
    experiment: float | None
    experimentUnit: float | None
    requireExperiment: float | None
    machine: float | None
    machineUnit: float | None
    requireMachine: float | None
    design: float | None
    designUnit: float | None
    requireDesign: float | None
    periodsPerWeek: float | None


class StageInfo(BaseModel):
    stage: bool | None
    stageNum: int | None
    stageGrantNum: int | None


class Education(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    enabled: bool | None
    bizTypeAssocs: list[int] | None
    bizTypeIds: list[int] | None
    transient: bool | None
    name: str | None


class CourseType(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    enabled: bool | None
    bizTypeAssocs: list[int] | None
    bizTypeIds: list[int] | None
    transient: bool | None
    name: str | None


class DefaultOpenDepart(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    code: str | None
    abbrZh: str | None
    abbrEn: str | None
    college: bool | None
    openCourse: bool | None
    experiment: bool | None
    simpleNameZh: str | None
    jmRemark: str | None


class DefaultExamMode(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    enabled: bool | None
    bizTypeAssocs: list[int] | None
    bizTypeIds: list[int] | None
    transient: bool | None
    name: str | None


class DefaultPreCourse(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    code: str | None
    periodInfo: PeriodInfo | None
    stageInfo: StageInfo | None
    credits: float | None
    calculateGp: bool | None
    theory: bool | None
    experiment: bool | None
    practice: bool | None
    test: bool | None
    machine: bool | None
    design: bool | None
    enabled: bool | None
    courseCategoryAssoc: int | None
    introduction: str | None


class BelongBizType(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None


class SuitableBizType(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None


class MngtDepartment(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    code: str | None
    abbrZh: str | None
    abbrEn: str | None
    college: bool | None
    openCourse: bool | None
    experiment: bool | None
    simpleNameZh: str | None
    jmRemark: str | None


class TeachLang(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    enabled: bool | None
    bizTypeAssocs: list[int] | None
    bizTypeIds: list[int] | None
    transient: bool | None
    name: str | None


class CourseCategory(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    enabled: bool | None
    suitableBizTypeAssocs: list[int] | None
    suitableBizTypeIds: list[int] | None
    transient: bool | None
    name: str | None


class CourseClassify(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    enabled: bool | None
    suitableBizTypeAssocs: list[int] | None
    suitableBizTypeIds: list[int] | None
    transient: bool | None
    name: str | None


class DisciplineType(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    enabled: bool | None
    bizTypeAssocs: list[int] | None
    bizTypeIds: list[int] | None
    transient: bool | None
    name: str | None


class CourseGradation(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    enabled: bool | None
    suitableBizTypeAssocs: list[int] | None
    educationAssoc: int | None
    suitableBizTypeIds: list[int] | None
    transient: bool | None
    name: str | None


class RankOption(BaseModel):
    rank: str | None
    score: float | None


class ScoreMarkStyle(BaseModel):
    id: int | None
    bizTypeAssoc: int | None
    name: str | None
    digit: bool | None
    maxScore: int | None
    maxScale: int | None
    enabled: bool | None
    rankOptions: list[RankOption] | None
    transient: bool | None


class MeritCourseType(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    enabled: bool | None
    bizTypeAssocs: list[int] | None
    bizTypeIds: list[int] | None
    transient: bool | None
    name: str | None


class LastExecuteSemester(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    calendarAssoc: int | None
    schoolYear: str | None
    startDate: str | None
    endDate: str | None
    weekStartOnSunday: bool | None
    countInTerm: bool | None
    season: str | None
    enabled: bool | None
    fileInfoAssoc: int | None
    currentYear: int | None
    simpleName: str | None
    transient: bool | None
    name: str | None


class Course(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    code: str | None
    periodInfo: PeriodInfo | None
    stageInfo: StageInfo | None
    credits: float | None
    calculateGp: bool | None
    theory: bool | None
    experiment: bool | None
    practice: bool | None
    test: bool | None
    machine: bool | None
    design: bool | None
    enabled: bool | None
    education: Education | None
    courseType: CourseType | None
    defaultOpenDepart: DefaultOpenDepart | None
    grantCourseLevel: int | None
    defaultExamMode: DefaultExamMode | None
    defaultPreCourses: list[DefaultPreCourse] | None
    belongBizType: BelongBizType | None
    suitableBizTypes: list[SuitableBizType] | None
    mngtDepartment: MngtDepartment | None
    teachLang: TeachLang | None
    courseCategory: CourseCategory | None
    courseClassify: CourseClassify | None
    disciplineType: DisciplineType | None
    courseGradation: CourseGradation | None
    inStoreDateTime: str | None
    outOfSchoolTeaching: bool | None
    scoreMarkStyle: ScoreMarkStyle | None
    syllabusAssoc: int | None
    introduction: str | None
    introductionEn: str | None
    socreStageNumStr: str | None
    designateTextbook: str | None
    referenceTextbook: str | None
    preCourseMode: bool | None
    remark: str | None
    canPersonalInput: bool | None
    meritCourseType: MeritCourseType | None
    seasons: list[str] | None
    lastExecuteSemester: LastExecuteSemester | None


class PreCourse(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    code: str | None
    periodInfo: PeriodInfo | None
    stageInfo: StageInfo | None
    credits: float | None
    calculateGp: bool | None
    theory: bool | None
    experiment: bool | None
    practice: bool | None
    test: bool | None
    machine: bool | None
    design: bool | None
    enabled: bool | None
    courseCategoryAssoc: int | None
    introduction: str | None


class OpenDepartment(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    code: str | None
    abbrZh: str | None
    abbrEn: str | None
    college: bool | None
    openCourse: bool | None
    experiment: bool | None
    simpleNameZh: str | None
    jmRemark: str | None


class ExamMode(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    enabled: bool | None
    bizTypeAssocs: list[int] | None
    bizTypeIds: list[int] | None
    transient: bool | None
    name: str | None


class Campus(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    code: str | None


class RoomType(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    enabled: bool | None
    bizTypeAssocs: list[int] | None
    bizTypeIds: list[int] | None
    transient: bool | None
    name: str | None


class ContactInfo(BaseModel):
    email: str | None
    telephone: str | None
    mobile: str | None
    address: str | None
    postcode: str | None
    qq: str | None
    wechat: str | None


class Gender(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    enabled: bool | None
    bizTypeAssocs: list[int] | None
    bizTypeIds: list[int] | None
    transient: bool | None
    name: str | None


class Person(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    idCardNumber: str | None
    country: str | None
    contactInfo: ContactInfo | None
    family: str | None
    portrait: str | None
    gender: Gender | None
    idCardType: str | None
    birthday: str | None
    nation: str | None
    politicalVisage: str | None
    age: int | None
    gid: str | None
    introduction: str | None
    personalPage: str | None


class Teacher(BaseModel):
    id: int | None
    code: str | None
    teaching: bool | None
    zaiZhi: bool | None
    hireType: str | None
    department: str | None
    person: Person | None
    title: str | None
    type: str | None
    teacherStation: str | None
    teacherEducation: str | None
    teacherDegree: str | None
    createdAt: str | None
    enrollDate: str | None


class PersonSummary(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    gid: str | None
    introduction: str | None
    code: str | None
    birthday: str | None
    personalPage: str | None


class TeacherLessonType(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    code: str | None
    role: str | None
    enabled: bool | None


class TeacherAssignmentListItem(BaseModel):
    teacher: Teacher | None
    person: PersonSummary | None
    role: str | None
    indexNo: int | None
    age: int | None
    title: str | None
    period: float | None
    teacherLessonType: TeacherLessonType | None
    contactInfo: ContactInfo | None
    weekIndices: list[int] | None
    weekIndicesMsg: str | None


class ClassType(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    enabled: bool | None
    bizTypeAssocs: list[int] | None
    bizTypeIds: list[int] | None
    transient: bool | None
    name: str | None


class TeachingMethod(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    enabled: bool | None
    bizTypeAssocs: list[int] | None
    bizTypeIds: list[int] | None
    transient: bool | None
    name: str | None


class TextbookType(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    enabled: bool | None
    bizTypeAssocs: list[int] | None
    bizTypeIds: list[int] | None
    transient: bool | None
    name: str | None


class TextbookGrade(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    enabled: bool | None
    bizTypeAssocs: list[int] | None
    bizTypeIds: list[int] | None
    transient: bool | None
    name: str | None


class Textbook(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    publish: bool | None
    author: str | None
    isbn: str | None
    publishingHouse: str | None
    edition: str | None
    dates: str | None
    price: float | None
    content: str | None
    remark: str | None
    enabled: bool | None
    textbookType: TextbookType | None
    textbookGrade: TextbookGrade | None
    semester: Semester | None
    dateStr: str | None


class JwForStdLessonSearchSemesterItem(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    code: str | None
    remark: str | None
    requiredPeriodInfo: RequiredPeriodInfo | None
    actualPeriods: float | None
    scheduleText: ScheduleText | None
    stdCount: int | None
    limitCount: int | None
    reserveCount: int | None
    suggestScheduleWeeks: list[int] | None
    calcRelatedAdminclasses: bool | None
    allowMakeup: bool | None
    expActualPeriods: int | None
    needAssign: bool | None
    auto: bool | None
    scheduleRemark: str | None
    timeTableLayout: TimeTableLayout | None
    bizType: BizType | None
    semester: Semester | None
    course: Course | None
    preCourses: list[PreCourse] | None
    courseType: CourseType | None
    openDepartment: OpenDepartment | None
    examMode: ExamMode | None
    campus: Campus | None
    teachLang: TeachLang | None
    roomType: RoomType | None
    suggestScheduleWeeksInfo: str | None
    scheduleWeeksInfo: str | None
    teacherAssignmentList: list[TeacherAssignmentListItem] | None
    scheduleStartWeek: int | None
    scheduleEndWeek: int | None
    planExamWeek: int | None
    adminclassIds: list[int] | None
    courseGradation: CourseGradation | None
    education: Education | None
    classType: ClassType | None
    credits: float | None
    teachingMethod: TeachingMethod | None
    outOfSchoolTeaching: bool | None
    textbook: str | None
    placementInfo: str | None
    nonSelectiveInfo: str | None
    selectionInfo: str | None
    compulsory: bool | None
    grade: str | None
    graduateAndPostgraduate: bool | None
    courseCategory: CourseCategory | None
    courseClassify: CourseClassify | None
    preCourseMode: bool | None
    selectedStdCount: int | None
    courseApplyLimit: int | None
    departEditClssList: bool | None
    introduction: str | None
    needTextbook: bool | None
    publish: bool | None
    textbooks: list[Textbook] | None
    preCourseText: str | None


class FieldPage(BaseModel):
    currentPage: int | None
    rowsInPage: int | None
    rowsPerPage: int | None
    totalRows: int | None
    totalPages: int | None


class FieldSort(BaseModel):
    field: str | None
    type: str | None
    typeString: str | None


class JwForStdLessonSearchSemesterResponse(BaseModel):
    data: list[JwForStdLessonSearchSemesterItem] | None
    field_page_: FieldPage | None = Field(..., alias="_page_")
    field_sorts_: list[FieldSort] | None = Field(..., alias="_sorts_")
