# generated by datamodel-codegen:
#   filename:  497890.json
#   timestamp: 2026-01-26T14:47:58+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class RequiredPeriodInfo(BaseModel):
    total: float
    weeks: int | None
    theory: float | None
    theoryUnit: None
    requireTheory: None
    practice: float | None
    practiceUnit: None
    requirePractice: None
    test: None
    testUnit: None
    requireTest: None
    experiment: float | None
    experimentUnit: None
    requireExperiment: None
    machine: None
    machineUnit: None
    requireMachine: None
    design: None
    designUnit: None
    requireDesign: None
    periodsPerWeek: float | None
    timesPerWeek: int | None


class DateTimeText(BaseModel):
    textZh: str | None
    textEn: str | None
    text: str | None


class DateTimePlaceText(BaseModel):
    textZh: str | None
    textEn: str | None
    text: str | None


class DateTimePlacePersonText(BaseModel):
    textZh: str | None
    textEn: str | None
    text: str | None


class RoomSeatText(BaseModel):
    textZh: str
    textEn: str
    text: str


class ScheduleText(BaseModel):
    dateTimeText: DateTimeText
    dateTimePlaceText: DateTimePlaceText
    dateTimePlacePersonText: DateTimePlacePersonText
    roomSeatText: RoomSeatText


class TimeTableLayout(BaseModel):
    id: int
    nameZh: str
    nameEn: str
    enabled: bool


class BizType(BaseModel):
    id: int
    nameZh: str
    nameEn: str


class Calendar(BaseModel):
    id: int
    nameZh: str
    nameEn: str


class Semester(BaseModel):
    id: int
    nameZh: str
    nameEn: str
    code: str
    calendar: Calendar
    schoolYear: str
    startDate: str
    endDate: str
    weekStartOnSunday: bool
    countInTerm: bool
    season: str
    enabled: bool
    fileInfo: None


class PeriodInfo(BaseModel):
    total: float
    weeks: int | None
    theory: float | None
    theoryUnit: None
    requireTheory: None
    practice: float | None
    practiceUnit: None
    requirePractice: None
    test: None
    testUnit: None
    requireTest: None
    experiment: float | None
    experimentUnit: None
    requireExperiment: None
    machine: None
    machineUnit: None
    requireMachine: None
    design: None
    designUnit: None
    requireDesign: None
    periodsPerWeek: float | None


class StageInfo(BaseModel):
    stage: bool
    stageNum: int | None
    stageGrantNum: int | None


class Education(BaseModel):
    nameZh: str
    nameEn: str
    id: int
    code: str
    enabled: bool
    bizTypeAssocs: list[int]
    bizTypeIds: list[int]
    transient: bool
    name: str


class CourseType(BaseModel):
    nameZh: str
    nameEn: str
    id: int
    code: str
    enabled: bool
    bizTypeAssocs: list[int]
    bizTypeIds: list[int]
    transient: bool
    name: str


class DefaultOpenDepart(BaseModel):
    id: int
    nameZh: str
    nameEn: str | None
    code: str
    abbrZh: str | None
    abbrEn: None
    college: bool
    openCourse: bool
    experiment: bool
    simpleNameZh: str
    jmRemark: str | None


class DefaultExamMode(BaseModel):
    nameZh: str
    nameEn: str
    id: int
    code: str
    enabled: bool
    bizTypeAssocs: list[int]
    bizTypeIds: list[int]
    transient: bool
    name: str


class PeriodInfo1(BaseModel):
    total: float
    weeks: int | None
    theory: float
    theoryUnit: None
    requireTheory: None
    practice: float | None
    practiceUnit: None
    requirePractice: None
    test: None
    testUnit: None
    requireTest: None
    experiment: float | None
    experimentUnit: None
    requireExperiment: None
    machine: None
    machineUnit: None
    requireMachine: None
    design: None
    designUnit: None
    requireDesign: None
    periodsPerWeek: float | None


class StageInfo1(BaseModel):
    stage: bool
    stageNum: int | None
    stageGrantNum: int | None


class DefaultPreCourse(BaseModel):
    id: int
    nameZh: str
    nameEn: str
    code: str
    periodInfo: PeriodInfo1
    stageInfo: StageInfo1
    credits: float
    calculateGp: bool
    theory: bool
    experiment: bool
    practice: bool
    test: bool
    machine: bool
    design: bool
    enabled: bool
    courseCategoryAssoc: int
    introduction: str


class BelongBizType(BaseModel):
    id: int
    nameZh: str
    nameEn: str


class SuitableBizType(BaseModel):
    id: int
    nameZh: str
    nameEn: str


class MngtDepartment(BaseModel):
    id: int
    nameZh: str
    nameEn: str
    code: str
    abbrZh: str | None
    abbrEn: None
    college: bool
    openCourse: bool
    experiment: bool
    simpleNameZh: str
    jmRemark: str | None


class TeachLang(BaseModel):
    nameZh: str
    nameEn: str
    id: int
    code: str
    enabled: bool
    bizTypeAssocs: list[int]
    bizTypeIds: list[int]
    transient: bool
    name: str


class CourseCategory(BaseModel):
    nameZh: str
    nameEn: str | None
    id: int
    code: str
    enabled: bool
    suitableBizTypeAssocs: list[int]
    suitableBizTypeIds: list[int]
    transient: bool
    name: str


class CourseClassify(BaseModel):
    nameZh: str
    nameEn: str | None
    id: int
    code: str
    enabled: bool
    suitableBizTypeAssocs: list[int]
    suitableBizTypeIds: list[int]
    transient: bool
    name: str


class DisciplineType(BaseModel):
    nameZh: str
    nameEn: str
    id: int
    code: str
    enabled: bool
    bizTypeAssocs: list[int]
    bizTypeIds: list[int]
    transient: bool
    name: str


class CourseGradation(BaseModel):
    nameZh: str
    nameEn: str
    id: int
    code: str
    enabled: bool
    suitableBizTypeAssocs: list[int]
    educationAssoc: int
    suitableBizTypeIds: list[int]
    transient: bool
    name: str


class RankOption(BaseModel):
    rank: str
    score: float


class ScoreMarkStyle(BaseModel):
    id: int
    bizTypeAssoc: int
    name: str
    digit: bool
    maxScore: int | None
    maxScale: int | None
    enabled: bool
    rankOptions: list[RankOption]
    transient: bool


class MeritCourseType(BaseModel):
    nameZh: str
    nameEn: str
    id: int
    code: str
    enabled: bool
    bizTypeAssocs: list[int]
    bizTypeIds: list[int]
    transient: bool
    name: str


class LastExecuteSemester(BaseModel):
    nameZh: str
    nameEn: str
    id: int
    code: str
    calendarAssoc: int
    schoolYear: str
    startDate: str
    endDate: str
    weekStartOnSunday: bool
    countInTerm: bool
    season: str
    enabled: bool
    fileInfoAssoc: None
    currentYear: int
    simpleName: str
    transient: bool
    name: str


class Course(BaseModel):
    id: int
    nameZh: str
    nameEn: str
    code: str
    periodInfo: PeriodInfo
    stageInfo: StageInfo
    credits: float
    calculateGp: bool
    theory: bool
    experiment: bool
    practice: bool
    test: bool
    machine: bool
    design: bool
    enabled: bool
    education: Education
    courseType: CourseType | None
    defaultOpenDepart: DefaultOpenDepart
    grantCourseLevel: None
    defaultExamMode: DefaultExamMode
    defaultPreCourses: list[DefaultPreCourse]
    belongBizType: BelongBizType
    suitableBizTypes: list[SuitableBizType]
    mngtDepartment: MngtDepartment
    teachLang: TeachLang
    courseCategory: CourseCategory
    courseClassify: CourseClassify | None
    disciplineType: DisciplineType
    courseGradation: CourseGradation
    inStoreDateTime: str | None
    outOfSchoolTeaching: bool
    scoreMarkStyle: ScoreMarkStyle
    syllabusAssoc: int | None
    introduction: str | None
    introductionEn: str | None
    socreStageNumStr: None
    designateTextbook: str | None
    referenceTextbook: str | None
    preCourseMode: bool
    remark: str | None
    canPersonalInput: bool
    meritCourseType: MeritCourseType | None
    seasons: list[str]
    lastExecuteSemester: LastExecuteSemester | None


class PreCourse(BaseModel):
    id: int
    nameZh: str
    nameEn: str
    code: str
    periodInfo: PeriodInfo1
    stageInfo: StageInfo1
    credits: float
    calculateGp: bool
    theory: bool
    experiment: bool
    practice: bool
    test: bool
    machine: bool
    design: bool
    enabled: bool
    courseCategoryAssoc: int
    introduction: str


class OpenDepartment(BaseModel):
    id: int
    nameZh: str
    nameEn: str | None
    code: str
    abbrZh: str | None
    abbrEn: None
    college: bool
    openCourse: bool
    experiment: bool
    simpleNameZh: str
    jmRemark: str | None


class ExamMode(BaseModel):
    nameZh: str
    nameEn: str
    id: int
    code: str
    enabled: bool
    bizTypeAssocs: list[int]
    bizTypeIds: list[int]
    transient: bool
    name: str


class Campus(BaseModel):
    id: int
    nameZh: str
    nameEn: str
    code: str


class RoomType(BaseModel):
    nameZh: str
    nameEn: str
    id: int
    code: str
    enabled: bool
    bizTypeAssocs: list[int]
    bizTypeIds: list[int]
    transient: bool
    name: str


class ContactInfo(BaseModel):
    email: None
    telephone: None
    mobile: None
    address: None
    postcode: None
    qq: None
    wechat: None


class Gender(BaseModel):
    nameZh: str
    nameEn: str
    id: int
    code: str
    enabled: bool
    bizTypeAssocs: list[int]
    bizTypeIds: list[int]
    transient: bool
    name: str


class Person(BaseModel):
    id: int
    nameZh: str
    nameEn: str | None
    idCardNumber: None
    country: None
    contactInfo: ContactInfo
    family: None
    portrait: None
    gender: Gender
    idCardType: None
    birthday: None
    nation: None
    politicalVisage: None
    age: None
    gid: None
    introduction: None
    personalPage: str | None


class Teacher(BaseModel):
    id: int
    code: None
    teaching: bool
    zaiZhi: bool
    hireType: None
    department: None
    person: Person
    title: None
    type: None
    teacherStation: None
    teacherEducation: None
    teacherDegree: None
    createdAt: str
    enrollDate: None


class Person1(BaseModel):
    id: int
    nameZh: str
    nameEn: str | None
    gid: None
    introduction: None
    code: None
    birthday: None
    personalPage: None


class TeacherLessonType(BaseModel):
    id: int
    nameZh: str
    nameEn: None
    code: str
    role: str
    enabled: bool


class TeacherAssignmentListItem(BaseModel):
    teacher: Teacher
    person: Person1
    role: str
    indexNo: int
    age: None
    title: None
    period: float | None
    teacherLessonType: TeacherLessonType | None
    contactInfo: None
    weekIndices: list[int]
    weekIndicesMsg: str | None


class ClassType(BaseModel):
    nameZh: str
    nameEn: str
    id: int
    code: str
    enabled: bool
    bizTypeAssocs: list[int]
    bizTypeIds: list[int]
    transient: bool
    name: str


class TeachingMethod(BaseModel):
    nameZh: str
    nameEn: str
    id: int
    code: str
    enabled: bool
    bizTypeAssocs: list[int]
    bizTypeIds: list[int]
    transient: bool
    name: str


class TextbookType(BaseModel):
    nameZh: str
    nameEn: str
    id: int
    code: str
    enabled: bool
    bizTypeAssocs: list[int]
    bizTypeIds: list[int]
    transient: bool
    name: str

class TextbookGrade(BaseModel):
    nameZh: str
    nameEn: str
    id: int
    code: str
    enabled: bool
    bizTypeAssocs: list[int]
    bizTypeIds: list[int]
    transient: bool
    name: str


class Semester1(BaseModel):
    id: int
    nameZh: str
    nameEn: str
    code: str
    calendar: Calendar
    schoolYear: str
    startDate: str
    endDate: str
    weekStartOnSunday: bool
    countInTerm: bool
    season: str
    enabled: bool
    fileInfo: None


class Textbook(BaseModel):
    id: int
    nameZh: str
    nameEn: None
    publish: bool
    author: str
    isbn: str | None
    publishingHouse: str | None
    edition: str | None
    dates: str | None
    price: None
    content: str | None
    remark: str | None
    enabled: bool
    textbookType: TextbookType | None
    textbookGrade: TextbookGrade | None
    semester: Semester1 | None
    dateStr: str


class Datum(BaseModel):
    id: int
    nameZh: str | None
    nameEn: None
    code: str
    remark: str | None
    requiredPeriodInfo: RequiredPeriodInfo
    actualPeriods: float
    scheduleText: ScheduleText
    stdCount: int
    limitCount: int
    reserveCount: int
    suggestScheduleWeeks: list[int]
    calcRelatedAdminclasses: bool
    allowMakeup: bool
    expActualPeriods: int
    needAssign: bool
    auto: bool
    scheduleRemark: str | None
    timeTableLayout: TimeTableLayout
    bizType: BizType
    semester: Semester
    course: Course
    preCourses: list[PreCourse]
    courseType: CourseType | None
    openDepartment: OpenDepartment
    examMode: ExamMode
    campus: Campus | None
    teachLang: TeachLang | None
    roomType: RoomType | None
    suggestScheduleWeeksInfo: str
    scheduleWeeksInfo: None
    teacherAssignmentList: list[TeacherAssignmentListItem]
    scheduleStartWeek: int | None
    scheduleEndWeek: int | None
    planExamWeek: int | None
    adminclassIds: list[int]
    courseGradation: CourseGradation | None
    education: Education
    classType: ClassType
    credits: float
    teachingMethod: TeachingMethod | None
    outOfSchoolTeaching: bool
    textbook: str | None
    placementInfo: str
    nonSelectiveInfo: None
    selectionInfo: None
    compulsory: bool | None
    grade: str | None
    graduateAndPostgraduate: bool
    courseCategory: CourseCategory
    courseClassify: CourseClassify | None
    preCourseMode: bool
    selectedStdCount: int
    courseApplyLimit: int
    departEditClssList: bool
    introduction: None
    needTextbook: bool | None
    publish: bool | None
    textbooks: list[Textbook]
    preCourseText: str


class FieldPage(BaseModel):
    currentPage: int
    rowsInPage: int
    rowsPerPage: int
    totalRows: int
    totalPages: int


class FieldSort(BaseModel):
    field: str
    type: str
    typeString: str


class Model(BaseModel):
    data: list[Datum]
    field_page_: FieldPage = Field(..., alias='_page_')
    field_sorts_: list[FieldSort] = Field(..., alias='_sorts_')
