# generated by datamodel-codegen:
#   filename:  160733.json
#   timestamp: 2026-01-26T14:51:23+00:00

from __future__ import annotations

from .base import UpstreamBaseModel as BaseModel


class Title(BaseModel):
    nameZh: str | None
    nameEn: str | None
    id: int | None
    code: str | None
    enabled: bool | None
    bizTypeAssocs: list[int] | None
    specialistPositionLevelAssoc: int | None
    bizTypeIds: list[int] | None
    transient: bool | None
    name: str | None


class TeacherLessonType(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    code: str | None
    role: str | None
    enabled: bool | None


class ContactInfo(BaseModel):
    email: str | None
    telephone: str | None
    mobile: str | None
    address: str | None
    postcode: str | None
    qq: str | None
    wechat: str | None


class TeacherAssignmentListItem(BaseModel):
    role: str | None
    code: str | None
    teacherId: int | None
    personId: int | None
    name: str | None
    age: int | None
    titleName: str | None
    title: Title | None
    period: float | None
    teacherLessonType: TeacherLessonType | None
    contactInfo: ContactInfo | None
    weekIndices: list[int] | None
    weekIndicesMsg: str | None


class RequiredPeriodInfo(BaseModel):
    total: float | None
    weeks: int | None
    theory: float | None
    theoryUnit: float | None
    requireTheory: float | None
    practice: float | None
    practiceUnit: float | None
    requirePractice: float | None
    test: float | None
    testUnit: float | None
    requireTest: float | None
    experiment: float | None
    experimentUnit: float | None
    requireExperiment: float | None
    machine: float | None
    machineUnit: float | None
    requireMachine: float | None
    design: float | None
    designUnit: float | None
    requireDesign: float | None
    periodsPerWeek: float | None
    timesPerWeek: int | None


class AdminClass(BaseModel):
    id: int | None
    code: str | None
    nameZh: str | None
    nameEn: str | None
    grade: str | None
    stdCount: int | None
    planCount: int | None
    enabled: bool | None
    abbrZh: str | None
    abbrEn: str | None
    name: str | None = None


class ScheduleJsonParam(BaseModel):
    lessonId: int | None
    scheduleGroupId: int | None
    scheduleId: int | None
    teacherId: int | None
    personId: int | None
    date: str | None
    weekday: int | None
    startTime: int | None
    endTime: int | None
    weekIndex: int | None
    startUnit: int | None
    endUnit: int | None


class LessonListItem(BaseModel):
    id: int | None
    code: str | None
    name: str | None
    courseId: int | None
    bizTypeId: int | None
    courseName: str | None
    courseTypeName: str | None
    teacherAssignmentList: list[TeacherAssignmentListItem] | None
    requiredPeriodInfo: RequiredPeriodInfo | None
    actualPeriods: float | None
    scheduleState: str | None
    limitCount: int | None
    stdCount: int | None
    suggestScheduleWeeks: list[int] | None
    suggestScheduleWeekInfo: str | None
    campusId: int | None
    roomTypeId: int | None
    adminclassIds: list[int] | None
    remark: str | None
    scheduleRemark: str | None
    adminclasses: list[AdminClass] | None
    scheduleJsonParams: list[ScheduleJsonParam] | None
    selectedStdCount: int | None


class Campus(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    code: str | None


class Building(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    code: str | None
    campus: Campus | None


class RoomType(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    code: str | None


class Room(BaseModel):
    id: int | None
    nameZh: str | None
    nameEn: str | None
    code: str | None
    building: Building | None
    roomType: RoomType | None
    floor: int | None
    virtual: bool | None
    seatsForLesson: int | None
    remark: str | None
    seats: int | None


class ScheduleListItem(BaseModel):
    lessonId: int | None
    scheduleGroupId: int | None
    periods: float | None
    date: str | None
    room: Room | None
    weekday: int | None
    startTime: int | None
    endTime: int | None
    teacherId: int | None
    personId: int | None
    personName: str | None
    experiment: bool | None
    customPlace: str | None
    lessonType: str | None
    weekIndex: int | None
    exerciseClass: bool | None
    startUnit: int | None
    endUnit: int | None


class ScheduleGroupListItem(BaseModel):
    id: int | None
    lessonId: int | None
    no: int | None
    limitCount: int | None
    stdCount: int | None
    actualPeriods: float | None
    default: bool | None


class ScheduleTableResult(BaseModel):
    lessonList: list[LessonListItem] | None
    scheduleList: list[ScheduleListItem] | None
    scheduleGroupList: list[ScheduleGroupListItem] | None


class JwWsScheduleTableDatumResponse(BaseModel):
    result: ScheduleTableResult | None
