# generated by datamodel-codegen:
#   filename:  160733.json
#   timestamp: 2026-01-26T14:51:23+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Title(BaseModel):
    nameZh: str
    nameEn: str | None
    id: int
    code: str
    enabled: bool
    bizTypeAssocs: list[int]
    specialistPositionLevelAssoc: int
    bizTypeIds: list[int]
    transient: bool
    name: str


class TeacherLessonType(BaseModel):
    id: int
    nameZh: str
    nameEn: str | None
    code: str
    role: str
    enabled: bool


class ContactInfo(BaseModel):
    email: None
    telephone: None
    mobile: None
    address: None
    postcode: None
    qq: None
    wechat: None


class TeacherAssignmentListItem(BaseModel):
    role: str
    code: str
    teacherId: int
    personId: int
    name: str
    age: int | None
    titleName: str | None
    title: Title | None
    period: float | None
    teacherLessonType: TeacherLessonType | None
    contactInfo: ContactInfo
    weekIndices: list[Any]
    weekIndicesMsg: str | None


class RequiredPeriodInfo(BaseModel):
    total: float | None
    weeks: int | None
    theory: float | None
    theoryUnit: float | None
    requireTheory: float | None
    practice: float | None
    practiceUnit: float | None
    requirePractice: float | None
    test: float | None
    testUnit: float | None
    requireTest: float | None
    experiment: float | None
    experimentUnit: float | None
    requireExperiment: float | None
    machine: float | None
    machineUnit: float | None
    requireMachine: float | None
    design: float | None
    designUnit: float | None
    requireDesign: float | None
    periodsPerWeek: float | None
    timesPerWeek: int | None


class LessonListItem(BaseModel):
    id: int
    code: str
    name: str | None
    courseId: int
    bizTypeId: int
    courseName: str
    courseTypeName: str
    teacherAssignmentList: list[TeacherAssignmentListItem]
    requiredPeriodInfo: RequiredPeriodInfo
    actualPeriods: float
    scheduleState: str
    limitCount: int
    stdCount: int
    suggestScheduleWeeks: list[int]
    suggestScheduleWeekInfo: str
    campusId: int | None
    roomTypeId: int | None
    adminclassIds: list[Any]
    remark: str | None
    scheduleRemark: str | None
    adminclasses: list[Any]
    scheduleJsonParams: list[Any]
    selectedStdCount: int


class Campus(BaseModel):
    id: int
    nameZh: str
    nameEn: str
    code: str


class Building(BaseModel):
    id: int
    nameZh: str
    nameEn: str
    code: str
    campus: Campus


class RoomType(BaseModel):
    id: int
    nameZh: str
    nameEn: str
    code: str


class Room(BaseModel):
    id: int
    nameZh: str
    nameEn: str
    code: str
    building: Building
    roomType: RoomType
    floor: int
    virtual: bool
    seatsForLesson: int
    remark: str | None
    seats: int


class ScheduleListItem(BaseModel):
    lessonId: int
    scheduleGroupId: int
    periods: float
    date: str
    room: Room | None
    weekday: int
    startTime: int
    endTime: int
    teacherId: int | None
    personId: int | None
    personName: str | None
    experiment: None
    customPlace: str | None
    lessonType: None
    weekIndex: int
    exerciseClass: bool | None
    startUnit: int
    endUnit: int


class ScheduleGroupListItem(BaseModel):
    id: int
    lessonId: int
    no: int
    limitCount: int
    stdCount: int
    actualPeriods: float
    default: bool


class Result(BaseModel):
    lessonList: list[LessonListItem]
    scheduleList: list[ScheduleListItem]
    scheduleGroupList: list[ScheduleGroupListItem]


class Model(BaseModel):
    result: Result
